### PR TITLE
Adding AWS documents

### PR DESCRIPTION
**Pull request by MCupp93**

### CODE REVIEW

**Comment by gregelin** [comment]
I merged too quickly. Looks like files are missing the `title:` key. I'm fixing.

**Comment by MCupp93** [comment]
oh darn it, I'll make sure that's the first thing I do tomorrow.

**Comment by gregelin** [comment]
@MCupp93 Are you launching the virtual machine in `vm` and checking?

**Comment by MCupp93** [comment]
Yeah and I also make all the changes and look at them in my text editor but I must have overlooked that for some reason or another.

**Comment by gregelin** [comment]
All fixed and deployed.

**Pull request merged**
