### PR TITLE
First half of Dept. of Education Docs

### PR DESCRIPTION
**Pull request by MCupp93**

### CODE REVIEW

**Comment by gregelin** [comment]
I think these are missing `title:` keys?

Can you show me how you are testing locally?

**Comment by MCupp93** [comment]
Okay. I feel like I must be missing something. What exactly is meant by title: Keys?

**Comment by gregelin** [comment]
Every file needs to have a title. 
Add a line in each file beginning with the key "title: " followed by title. See other files for example.

**Comment by MCupp93** [comment]
Okay I see what I did wrong now. The DoD ones have them but for some reason I neglected to push the changes to the AWS documents with the titles in them.. Going to create a new pull request.

**Comment by gregelin** [comment]
Did you pull before updating? Have I shown you how to do that?

**Comment by MCupp93** [comment]
I thought I did, in the command line it said everything was up to date. But now on github and in the command line when trying to do it it is telling me there is conflicts and won't let me merge.

**Comment by MCupp93** [comment]
I think I see the problem. I thought I had done the pull correctly but it's looking like I did something wrong. And now that I've done it correctly it pulled in your changes to the AWS docs and there is now a conflict. I think I'm going to need assistance resolving it, I've tried looking it up but can't seem to get it.

**Comment by gregelin** [comment]
No worries. All good learning. 

There is pulling into your local version from your repo, then there is pulling in the upstream origin into your repo. 

Conflicts are easier to resolve than you would think. Give a couple a try.

**Pull request closed without merging**
